[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production]
  # You can also add environment variables here
  environment = { NODE_VERSION = "18" }
